[package]
name = "fimo_std_macros"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
description = "Proc-macros of the fimo_std crate"

[lib]
proc-macro = true

[lints]
workspace = true

[dependencies.proc-macro2]
version = "1.0"

[dependencies.syn]
version = "2.0.96"
features = ["visit", "full"]

[dependencies.quote]
version = "1.0"

[dependencies.semver]
version = "1.0"
